title: custodian
email: ongsp@ucsd.edu
description: >- # this means to ignore newlines until "baseurl:"
  Python Materials Genomics (custodian) is a robust materials analysis code that
  defines classes for structures and molecules with support for many electronic
  structure codes. It powers the Materials Project.
baseurl: ""
url: https://custodian.org
# twitter_username: custodian
github_username: materialsproject

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

favicon_ico: /assets/favicon.ico

aux_links:
  GitHub: [https://github.com/materialsproject/custodian]
  Issues: [https://github.com/materialsproject/custodian/issues]
  Discourse: [https://matsci.org/custodian]
  Materials Project: [https://materialsproject.org]
