name: Test, Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        sudo apt-get install python-openbabel
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-optional.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: pytest
      run: |
        pytest custodian --color=yes
    - name: release
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*.tar.gz
