name: Testing

on:
  push:
    branches: [master]
    paths-ignore: [docs/**]
  pull_request:
    branches: [master]
    paths-ignore: [docs/**]
  workflow_dispatch:
  # make this workflow reusable by release.yml
  workflow_call:

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: tests/requirements**.txt

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: myenv

      - name: Install OpenBabel
        run: conda install -c conda-forge openbabel

      - name: Install dependencies
        run: pip install .[dev]

      - name: pytest
        env:
          PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
          MPLBACKEND: "Agg"
        run: pytest --cov=custodian --color=yes tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
